import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Contribot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/favico.png" />
      </Head> 
      <Header/>
      <Hero />
      <Footer/>
      </>
      )
}
  
       

